### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by psegovias** [Gyvastis/twbot-php#1]
Any guide?

**Comment by Gyvastis** [comment]
It's not yet in a release state.

**Comment by psegovias** [comment]
OK, you will release it someday?

**Comment by Gyvastis** [comment]
Maybe :+1:

**Comment by psegovias** [comment]
Nice! :+1:

**Comment by psegovias** [comment]
Any news? :+1:

**Comment by psegovias** [comment]
Any news? @Gyvastis  :+1:

**Comment by Gyvastis** [comment]
I am currently developing a v2 based on Symfony framework and dropped using this one. Though I could make a guide & release this as it is, so you could run it :)

**Comment by psegovias** [comment]
thanks!
that would be very good! when you could do it? :+1:
